// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WPF.Translations.VSEx
{
    internal sealed partial class Vsix
    {
        public const string Id = "WPF.Translations.VSEx.ade07114-ae00-40bb-aba2-92fdad6f2b1c";
        public const string Name = "WPF.Translations Visual Studio Extension";
        public const string Description = @"A Visual Studio extension to help manage a collection of strings to translate. Strings are kept in a XAML ResourceDictionary (Translations.[culture].xaml) or a text file (Translations.[culture].txt). Add a string or remove a string and that string is added or removed from all translation files.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Aaron Amberman";
        public const string Tags = "WPF.Translation,WPF.Translations,WPF.Translations.TranslationBinding,WPF translation,WPF translations,WPF translatable strings";
    }
}
