// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WPF.Translations.VSEx
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSExString = "2817b031-86f1-4cde-894c-25b60903df95";
        public static Guid VSEx = new Guid(VSExString);

        public const string guidVSExPackageCmdSetString = "f1217d2a-40d8-4659-afdc-88128592d174";
        public static Guid guidVSExPackageCmdSet = new Guid(guidVSExPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidTranslationStringsToolWindowCommand = 0x0100;
    }
}